homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 28
  unit_system: metric
  time_zone: Europe/Stockholm

#tibber:
#  access_token: !secret tibber-token
# Enables a bunch of components with autoconfig
config:
frontend:
#updater:
discovery:
history:
sun:
#ios:
#homekit:
system_health:
#mobile_app:

#http:
#  api_password: !secret http_password

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# View all events in a logbook
#logbook:

# Text to speech
#tts:
#  platform: google

default_config:

mqtt:
  broker: 10.0.1.210

sonos:

recorder:
  commit_interval: 1
  purge_keep_days: 7

influxdb:
  host: 10.0.1.3
  username: home-assistant
  password: !secret influx_password

#input_boolean: !include input_boolean.yaml
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
climate: !include_dir_merge_list climate
#utility_meter:
#  energy:
#    source: sensor.heat_pump_kwh
#    cycle: hourly
