homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 23
  unit_system: metric
  time_zone: Europe/Stockholm
  customize:
    sensor.solel_just_nu:
      homebridge_sensor_type: light
      homebridge_name: Solar power
      homebridge_visible: true
    input_boolean.doorbell:
      homebridge_visible: true
    media_player.tvrum:
      homebridge_visible: true
    input_boolean.appletv_playing:
      homebridge_visible: true
    input_boolean.doorbell:
      homebridge_visible: true

# Enables a bunch of components with autoconfig
frontend:
introduction:
updater:
discovery:
history:
sun:
ios:

http:
  api_password: !secret http_password

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# View all events in a logbook
#logbook:

# Text to speech
#tts:
#  platform: google


mqtt:
  broker: 10.0.1.210
  username: pi
  password: !secret mqtt_password

media_player:
  - platform: sonos
  - platform: plex

recorder:
  purge_interval: 1
  purge_keep_days: 14

influxdb:
  host: 10.0.1.3
  username: home-assistant
  password: !secret influx_password

input_boolean: !include input_boolean.yaml
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
